### ISSUE TITLE
How can I add aliases in sportpaper.yml?

### ISSUE THREAD

**Issue by alejopca** [Electroid/SportPaper#20]
I understand that sportpaper hasn't commands.yml to alias some commands and instead you should do it in sportpaper.yml but, how do I?

**Comment by Brottweiler** [comment]
I would think this is the approach.
```yml
commands:
  aliases:
    icanhasbukkit:
    - version $1-
```
I haven't tested it myself because I actually didn't know about this, but I just applied it to our server and is waiting to see if it worked.
